CREATE TABLE STUDENTS (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    age INT,
    marks INT
);

INSERT INTO STUDENTS VALUES (1, 'Alice', 20, 85);
INSERT INTO STUDENTS VALUES (2, 'Bob', 22, 65);
INSERT INTO STUDENTS VALUES (3, 'Charlie', 21, 90);
INSERT INTO STUDENTS VALUES (4, 'Diana', 23, 70);
INSERT INTO STUDENTS VALUES (5, 'Ethan', 20, 78);

SELECT * FROM STUDENTS;

SELECT * FROM STUDENTS WHERE marks > 75;

SELECT * FROM STUDENTS ORDER BY age;
